--- #YAML:1.0
name:                Devel-Symdump
version:             2.0603
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.3004
author:              ~
distribution_type:   module
requires:     
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
